services:
  connect-1:
    image: redpandadata/connectors:v1.0.15
    container_name: redpanda-connect-1
    restart: unless-stopped
    # network_mode: host
    ports:
      - 8083:8083
    volumes:
      - ./connect-plugins:/opt/kafka/connect-plugins
    environment:
      CONNECT_CONFIGURATION: |
        key.converter=org.apache.kafka.connect.storage.StringConverter
        value.converter=org.apache.kafka.connect.storage.StringConverter
        group.id=connectors-group
        offset.storage.topic=_connectors_offsets
        config.storage.topic=_connectors_configs
        status.storage.topic=_connectors_status
        config.storage.replication.factor=1
        offset.storage.replication.factor=1
        status.storage.replication.factor=1
        offset.flush.interval.ms=10000
        consumer.override.auto.offset.reset=latest
      CONNECT_BOOTSTRAP_SERVERS: ${KAFKA_BROKER_URLS}
      # CONNECT_REST_ADVERTISED_HOST_NAME: ${CONNECT_CLUSTER_HOST_ADDRESS}
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: ${SCHEMA_REGISTRY_URL}
      CONNECT_PLUGIN_PATH: "/opt/kafka/connect-plugins"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      # Force JVM to prefer IPv4
      # JAVA_TOOL_OPTIONS: -Djava.net.preferIPv4Stack=true
