catalog:
  default:
    uri: http://iceberg-rest:8181
    s3.endpoint: https://ewr1.vultrobjects.com
    s3.access-key-id: ${AWS_ACCESS_KEY_ID}
    s3.secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    s3.region: ewr1
