services:
  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    networks:
      redpanda-net:
    depends_on:
      - iceberg-rest-catalog
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks/notebooks
      - ./.pyiceberg.yaml:/root/.pyiceberg.yaml
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ewr1
    ports:
      - 8888:8888
      - 8080:8080
      - 10000:10000
      - 10001:10001

  iceberg-rest-catalog:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    networks:
      redpanda-net:
    ports:
      - 8181:8181
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ewr1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=https://ewr1.vultrobjects.com

networks:
  redpanda-net:
    external: true
