services:
  flink-jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-jobmanager
    restart: unless-stopped
    ports:
      - "28081:8081" # Flink Web UI
    volumes:
      - /home/yampa/workspace/yampa/flink/flink-jobs:/opt/flink-jobs
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - redpanda-net

  flink-taskmanager-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-taskmanager-1
    restart: unless-stopped
    depends_on:
      - flink-jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
    networks:
      - redpanda-net

networks:
  redpanda-net:
    external: true
