services:
  redpanda-1:
    image: redpandadata/redpanda:v24.1.7
    container_name: redpanda-1
    restart: unless-stopped
    networks:
      - redpanda-net
    volumes:
      - "redpanda-1-data:/var/lib/redpanda/data"
    command:
      - redpanda start
      - --smp 1
      - --node-id 1
      - --kafka-addr INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr INSIDE://redpanda-1:29092,OUTSIDE://${REDPANDA_CLUSTER_HOST_ADDRESS}:9092
      - --pandaproxy-addr INSIDE://0.0.0.0:28082,OUTSIDE://0.0.0.0:8082
      - --advertise-pandaproxy-addr INSIDE://redpanda-1:28082,OUTSIDE://${REDPANDA_CLUSTER_HOST_ADDRESS}:8082
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr redpanda-1:33145
      - --set redpanda.enable_idempotence=true
      - --set redpanda.enable_transactions=true
      - --set redpanda.auto_create_topics_enabled=true
      - --set redpanda.default_topic_replications=1
      - --set redpanda.default_topic_partitions=4
      - --set redpanda.log_cleanup_policy=compact # compact, delete
      - --set redpanda.log_segment_ms=86400000 # Always close segment after 24 hours. Segments may be closed sooner if they reach the segment size limit (default 1GB).
      - --set redpanda.log_retention_ms=86400000 # Mark a log segment for deletion 24 hours after it is closed. Messages may be deleted sooner if they reach the retention size limit (default 1GB).
      - --set redpanda.log_compression_type=producer # producer, gzip, lz4, snappy, zstd
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092
      - 9644:9644

  console:
    image: redpandadata/console:v2.4.1
    container_name: redpanda-console
    restart: unless-stopped
    networks:
      - redpanda-net
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-1:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-1:8081"]
        connect:
          enabled: true
          clusters:
            - name: Primary
              url: http://${CONNECT_CLUSTER_HOST_ADDRESS}:8083
    ports:
      - "8080:8080"
    depends_on:
      - redpanda-1

networks:
  redpanda-net:
    external: true

volumes:
  redpanda-1-data:
