services:
  topics:
    image: redpandadata/redpanda:v23.3.4
    container_name: stream-topics
    networks:
      - redpanda-net
    entrypoint: /bin/sh
    command: >
      -c "
      echo 'Waiting for Redpanda to start...';
      until rpk --brokers=redpanda-1:29092 cluster info; do
        sleep 5;
      done;
      echo 'Redpanda started, creating topics...';
      rpk topic create trades --brokers=redpanda-1:29092 -c cleanup.policy=delete;
      echo 'Topics created successfully.';
      "

  coincap-crypto-streams:
    build: .
    container_name: coincap-crypto-streams
    restart: unless-stopped
    networks:
      - redpanda-net
    env_file:
      - ./yampa.env
    command: stream coincap --kafka --quiet --topic trades
    depends_on:
      - topics

networks:
  redpanda-net:
    external: true
